name: Deploy to Xserver

on:
  push:
    branches:
      - main   # mainブランチにpushしたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: festsnct.xsrv.jp
          username: festsnct
          key: ${{ secrets.XSERVER_SSH_KEY }}
          script: |
            cd /home/festsnct/fest-snct.jp/public_html/2026
            git fetch origin
            git merge origin/main
